# Generated by Django 3.0.4 on 2020-03-05 08:57

import django.contrib.auth.models
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('gram', '0002_image_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='comments',
            field=models.TextField(default=django.utils.timezone.now, max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='image',
            name='likes',
            field=models.PositiveIntegerField(default=0, verbose_name=django.contrib.auth.models.User),
        ),
    ]
