# Generated by Django 3.0.4 on 2020-03-12 20:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gram', '0002_image_likes'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Like',
        ),
    ]
