# Generated by Django 3.0.4 on 2020-03-05 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gram', '0003_auto_20200305_1157'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.TextField(max_length=50)),
                ('last_name', models.TextField(max_length=50)),
                ('profile_picture', models.ImageField(upload_to='prof_images')),
                ('bio', models.TextField(max_length=120)),
            ],
        ),
        migrations.AlterField(
            model_name='image',
            name='image_caption',
            field=models.TextField(max_length=100),
        ),
        migrations.AlterField(
            model_name='image',
            name='image_name',
            field=models.TextField(max_length=50),
        ),
        migrations.AlterField(
            model_name='image',
            name='likes',
            field=models.PositiveIntegerField(default=0, verbose_name='Likes'),
        ),
    ]
